//! Bulk operations for Issue entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateIssueDto;
use crate::application::service::IssueService;
use crate::domain::entity::Issue;

/// Bulk operation handler for Issue entities.
///
/// Wraps `IssueService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type IssueBulkService = GenericBulkService<Issue, CreateIssueDto, IssueService>;

// <<< CUSTOM
// END CUSTOM
