//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod issue_bulk;
pub mod service_level_agreement_bulk;
pub mod service_level_priority_bulk;
pub mod warranty_claim_bulk;

pub use issue_bulk::IssueBulkService;
pub use service_level_agreement_bulk::ServiceLevelAgreementBulkService;
pub use service_level_priority_bulk::ServiceLevelPriorityBulkService;
pub use warranty_claim_bulk::WarrantyClaimBulkService;

// <<< CUSTOM
// END CUSTOM
