//! Bulk operations for ServiceLevelAgreement entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateServiceLevelAgreementDto;
use crate::application::service::ServiceLevelAgreementService;
use crate::domain::entity::ServiceLevelAgreement;

/// Bulk operation handler for ServiceLevelAgreement entities.
///
/// Wraps `ServiceLevelAgreementService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ServiceLevelAgreementBulkService = GenericBulkService<ServiceLevelAgreement, CreateServiceLevelAgreementDto, ServiceLevelAgreementService>;

// <<< CUSTOM
// END CUSTOM
