//! Bulk operations for ServiceLevelPriority entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateServiceLevelPriorityDto;
use crate::application::service::ServiceLevelPriorityService;
use crate::domain::entity::ServiceLevelPriority;

/// Bulk operation handler for ServiceLevelPriority entities.
///
/// Wraps `ServiceLevelPriorityService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ServiceLevelPriorityBulkService = GenericBulkService<ServiceLevelPriority, CreateServiceLevelPriorityDto, ServiceLevelPriorityService>;

// <<< CUSTOM
// END CUSTOM
