//! Bulk operations for WarrantyClaim entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateWarrantyClaimDto;
use crate::application::service::WarrantyClaimService;
use crate::domain::entity::WarrantyClaim;

/// Bulk operation handler for WarrantyClaim entities.
///
/// Wraps `WarrantyClaimService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type WarrantyClaimBulkService = GenericBulkService<WarrantyClaim, CreateWarrantyClaimDto, WarrantyClaimService>;

// <<< CUSTOM
// END CUSTOM
