//! Issue DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Issue;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::AgreementStatus;
use crate::domain::entity::IssuePriority;
use crate::domain::entity::IssueStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Issue
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateIssueDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "customer_id")]
    pub customer_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subject: String,
    #[cfg_attr(feature = "validation", validate(length(max = 4000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub priority: IssuePriority,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sla_id")]
    pub sla_id: Option<Uuid>,
    pub status: IssueStatus,
    #[serde(alias = "agreement_status")]
    pub agreement_status: AgreementStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "opened_at")]
    pub opened_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "response_by")]
    pub response_by: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "resolution_by")]
    pub resolution_by: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "first_responded_at")]
    pub first_responded_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "response_breached")]
    pub response_breached: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "resolved_at")]
    pub resolved_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "paused_at")]
    pub paused_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "total_paused_mins")]
    pub total_paused_mins: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "escalated_project_id")]
    pub escalated_project_id: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Issue
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateIssueDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "customer_id")]
    pub customer_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subject: String,
    #[cfg_attr(feature = "validation", validate(length(max = 4000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub priority: IssuePriority,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sla_id")]
    pub sla_id: Option<Uuid>,
    pub status: IssueStatus,
    #[serde(alias = "agreement_status")]
    pub agreement_status: AgreementStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "opened_at")]
    pub opened_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "response_by")]
    pub response_by: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "resolution_by")]
    pub resolution_by: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "first_responded_at")]
    pub first_responded_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "response_breached")]
    pub response_breached: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "resolved_at")]
    pub resolved_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "paused_at")]
    pub paused_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "total_paused_mins")]
    pub total_paused_mins: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "escalated_project_id")]
    pub escalated_project_id: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Issue
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchIssueDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "customer_id")]
    pub customer_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 4000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub priority: Option<IssuePriority>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "sla_id")]
    pub sla_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<IssueStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "agreement_status")]
    pub agreement_status: Option<AgreementStatus>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "opened_at")]
    pub opened_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "response_by")]
    pub response_by: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "resolution_by")]
    pub resolution_by: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "first_responded_at")]
    pub first_responded_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "response_breached")]
    pub response_breached: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "resolved_at")]
    pub resolved_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "paused_at")]
    pub paused_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "total_paused_mins")]
    pub total_paused_mins: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "escalated_project_id")]
    pub escalated_project_id: Option<Uuid>,
}

impl PatchIssueDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.customer_id.is_some() || self.subject.is_some() || self.description.is_some() || self.priority.is_some() || self.sla_id.is_some() || self.status.is_some() || self.agreement_status.is_some() || self.opened_at.is_some() || self.response_by.is_some() || self.resolution_by.is_some() || self.first_responded_at.is_some() || self.response_breached.is_some() || self.resolved_at.is_some() || self.paused_at.is_some() || self.total_paused_mins.is_some() || self.escalated_project_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Issue entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct IssueResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub customer_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subject: String,
    pub description: Option<String>,
    pub priority: IssuePriority,
    pub sla_id: Option<Uuid>,
    pub status: IssueStatus,
    pub agreement_status: AgreementStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub opened_at: DateTime<Utc>,
    pub response_by: Option<DateTime<Utc>>,
    pub resolution_by: Option<DateTime<Utc>>,
    pub first_responded_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub response_breached: bool,
    pub resolved_at: Option<DateTime<Utc>>,
    pub paused_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub total_paused_mins: i32,
    pub escalated_project_id: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Issue entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct IssueListResponseDto {
    /// List of items
    pub items: Vec<IssueResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl IssueListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<IssueResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct IssueSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub customer_id: Option<Uuid>,
    pub subject: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Issue> for IssueResponseDto {
    fn from(entity: Issue) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            customer_id: entity.customer_id,
            subject: entity.subject,
            description: entity.description,
            priority: entity.priority,
            sla_id: entity.sla_id,
            status: entity.status,
            agreement_status: entity.agreement_status,
            opened_at: entity.opened_at,
            response_by: entity.response_by,
            resolution_by: entity.resolution_by,
            first_responded_at: entity.first_responded_at,
            response_breached: entity.response_breached,
            resolved_at: entity.resolved_at,
            paused_at: entity.paused_at,
            total_paused_mins: entity.total_paused_mins,
            escalated_project_id: entity.escalated_project_id,
            metadata: entity.metadata,
        }
    }
}

impl From<Issue> for IssueSummaryDto {
    fn from(entity: Issue) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            customer_id: entity.customer_id,
            subject: entity.subject,
            created_at,
        }
    }
}

impl From<CreateIssueDto> for Issue {
    fn from(dto: CreateIssueDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            customer_id: dto.customer_id,
            subject: dto.subject,
            description: dto.description,
            priority: dto.priority,
            sla_id: dto.sla_id,
            status: dto.status,
            agreement_status: dto.agreement_status,
            opened_at: dto.opened_at,
            response_by: dto.response_by,
            resolution_by: dto.resolution_by,
            first_responded_at: dto.first_responded_at,
            response_breached: dto.response_breached,
            resolved_at: dto.resolved_at,
            paused_at: dto.paused_at,
            total_paused_mins: dto.total_paused_mins,
            escalated_project_id: dto.escalated_project_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Issue> for IssueResponseDto {
    fn from(entity: &Issue) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            customer_id: entity.customer_id.clone(),
            subject: entity.subject.clone(),
            description: entity.description.clone(),
            priority: entity.priority.clone(),
            sla_id: entity.sla_id.clone(),
            status: entity.status.clone(),
            agreement_status: entity.agreement_status.clone(),
            opened_at: entity.opened_at.clone(),
            response_by: entity.response_by.clone(),
            resolution_by: entity.resolution_by.clone(),
            first_responded_at: entity.first_responded_at.clone(),
            response_breached: entity.response_breached.clone(),
            resolved_at: entity.resolved_at.clone(),
            paused_at: entity.paused_at.clone(),
            total_paused_mins: entity.total_paused_mins.clone(),
            escalated_project_id: entity.escalated_project_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateIssueDto> for Issue {
    fn from_create_dto(dto: CreateIssueDto) -> backbone_core::ServiceResult<Self> {
        Ok(Issue::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateIssueDto> for Issue {
    fn apply_update(mut self, dto: UpdateIssueDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.customer_id = dto.customer_id;
        self.subject = dto.subject;
        self.description = dto.description;
        self.priority = dto.priority;
        self.sla_id = dto.sla_id;
        self.status = dto.status;
        self.agreement_status = dto.agreement_status;
        self.opened_at = dto.opened_at;
        self.response_by = dto.response_by;
        self.resolution_by = dto.resolution_by;
        self.first_responded_at = dto.first_responded_at;
        self.response_breached = dto.response_breached;
        self.resolved_at = dto.resolved_at;
        self.paused_at = dto.paused_at;
        self.total_paused_mins = dto.total_paused_mins;
        self.escalated_project_id = dto.escalated_project_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Issue here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
