//! WarrantyClaim DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::WarrantyClaim;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::WarrantyStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new WarrantyClaim
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateWarrantyClaimDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "customer_id")]
    pub customer_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "serial_no")]
    pub serial_no: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "claim_date")]
    pub claim_date: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "warranty_expiry")]
    pub warranty_expiry: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_under_warranty")]
    pub is_under_warranty: bool,
    pub status: WarrantyStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "issue_id")]
    pub issue_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolution: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a WarrantyClaim
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateWarrantyClaimDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "customer_id")]
    pub customer_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "serial_no")]
    pub serial_no: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "claim_date")]
    pub claim_date: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "warranty_expiry")]
    pub warranty_expiry: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_under_warranty")]
    pub is_under_warranty: bool,
    pub status: WarrantyStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "issue_id")]
    pub issue_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolution: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a WarrantyClaim
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchWarrantyClaimDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "customer_id")]
    pub customer_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "serial_no")]
    pub serial_no: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "claim_date")]
    pub claim_date: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "warranty_expiry")]
    pub warranty_expiry: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_under_warranty")]
    pub is_under_warranty: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<WarrantyStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "issue_id")]
    pub issue_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resolution: Option<String>,
}

impl PatchWarrantyClaimDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.customer_id.is_some() || self.item_id.is_some() || self.serial_no.is_some() || self.claim_date.is_some() || self.warranty_expiry.is_some() || self.is_under_warranty.is_some() || self.status.is_some() || self.issue_id.is_some() || self.description.is_some() || self.resolution.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for WarrantyClaim entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WarrantyClaimResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub customer_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub item_id: Uuid,
    pub serial_no: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub claim_date: DateTime<Utc>,
    pub warranty_expiry: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_under_warranty: bool,
    pub status: WarrantyStatus,
    pub issue_id: Option<Uuid>,
    pub description: Option<String>,
    pub resolution: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for WarrantyClaim entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WarrantyClaimListResponseDto {
    /// List of items
    pub items: Vec<WarrantyClaimResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl WarrantyClaimListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<WarrantyClaimResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct WarrantyClaimSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub customer_id: Option<Uuid>,
    pub item_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<WarrantyClaim> for WarrantyClaimResponseDto {
    fn from(entity: WarrantyClaim) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            customer_id: entity.customer_id,
            item_id: entity.item_id,
            serial_no: entity.serial_no,
            claim_date: entity.claim_date,
            warranty_expiry: entity.warranty_expiry,
            is_under_warranty: entity.is_under_warranty,
            status: entity.status,
            issue_id: entity.issue_id,
            description: entity.description,
            resolution: entity.resolution,
            metadata: entity.metadata,
        }
    }
}

impl From<WarrantyClaim> for WarrantyClaimSummaryDto {
    fn from(entity: WarrantyClaim) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            customer_id: entity.customer_id,
            item_id: entity.item_id,
            created_at,
        }
    }
}

impl From<CreateWarrantyClaimDto> for WarrantyClaim {
    fn from(dto: CreateWarrantyClaimDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            customer_id: dto.customer_id,
            item_id: dto.item_id,
            serial_no: dto.serial_no,
            claim_date: dto.claim_date,
            warranty_expiry: dto.warranty_expiry,
            is_under_warranty: dto.is_under_warranty,
            status: dto.status,
            issue_id: dto.issue_id,
            description: dto.description,
            resolution: dto.resolution,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&WarrantyClaim> for WarrantyClaimResponseDto {
    fn from(entity: &WarrantyClaim) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            customer_id: entity.customer_id.clone(),
            item_id: entity.item_id.clone(),
            serial_no: entity.serial_no.clone(),
            claim_date: entity.claim_date.clone(),
            warranty_expiry: entity.warranty_expiry.clone(),
            is_under_warranty: entity.is_under_warranty.clone(),
            status: entity.status.clone(),
            issue_id: entity.issue_id.clone(),
            description: entity.description.clone(),
            resolution: entity.resolution.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateWarrantyClaimDto> for WarrantyClaim {
    fn from_create_dto(dto: CreateWarrantyClaimDto) -> backbone_core::ServiceResult<Self> {
        Ok(WarrantyClaim::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateWarrantyClaimDto> for WarrantyClaim {
    fn apply_update(mut self, dto: UpdateWarrantyClaimDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.customer_id = dto.customer_id;
        self.item_id = dto.item_id;
        self.serial_no = dto.serial_no;
        self.claim_date = dto.claim_date;
        self.warranty_expiry = dto.warranty_expiry;
        self.is_under_warranty = dto.is_under_warranty;
        self.status = dto.status;
        self.issue_id = dto.issue_id;
        self.description = dto.description;
        self.resolution = dto.resolution;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to WarrantyClaim here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
