//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod issue_specification;
pub mod service_level_agreement_specification;
pub mod service_level_priority_specification;
pub mod warranty_claim_specification;

// <<< CUSTOM
// END CUSTOM
