//! Domain policy for ServiceLevelAgreement aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::ServiceLevelAgreement;

/// Domain policy for ServiceLevelAgreement — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<ServiceLevelAgreement>` in the `// <<< CUSTOM` zone.
pub type ServiceLevelAgreementDomainPolicy = PermitAllPolicy<ServiceLevelAgreement>;

// <<< CUSTOM
// END CUSTOM
