//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod issue_service;
pub mod service_level_agreement_service;
pub mod service_level_priority_service;
pub mod warranty_claim_service;

// <<< CUSTOM
pub mod support_events;
pub mod support_ports;
pub mod support_write_service;
// END CUSTOM

pub use issue_service::IssueService;
pub use service_level_agreement_service::ServiceLevelAgreementService;
pub use service_level_priority_service::ServiceLevelPriorityService;
pub use warranty_claim_service::WarrantyClaimService;
// <<< CUSTOM
pub use support_events::{
    IssueEscalated, IssueResolved, LoggingSink, SupportEvent, SupportEventSink, WarrantyClaimFiled,
};
pub use support_ports::{ProjectAck, ProjectFromIssue, ProjectPort, SupportRejected};
pub use support_write_service::{
    NewIssue, NewSla, NewSlaPriority, NewWarrantyClaim, SupportError, SupportWriteService,
};
// END CUSTOM