//! Application service for ServiceLevelAgreement entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `service_level_agreement_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateServiceLevelAgreementDto, UpdateServiceLevelAgreementDto};
use crate::domain::entity::ServiceLevelAgreement;
use crate::infrastructure::persistence::ServiceLevelAgreementRepository;

/// Application service for ServiceLevelAgreement entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `service_level_agreement_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ServiceLevelAgreementServiceCustom {
///     inner: Arc<ServiceLevelAgreementService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ServiceLevelAgreementService = GenericCrudService<
    ServiceLevelAgreement,
    CreateServiceLevelAgreementDto,
    UpdateServiceLevelAgreementDto,
    ServiceLevelAgreementRepository,
>;

// <<< CUSTOM
// END CUSTOM
