//! Application service for ServiceLevelPriority entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `service_level_priority_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateServiceLevelPriorityDto, UpdateServiceLevelPriorityDto};
use crate::domain::entity::ServiceLevelPriority;
use crate::infrastructure::persistence::ServiceLevelPriorityRepository;

/// Application service for ServiceLevelPriority entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `service_level_priority_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ServiceLevelPriorityServiceCustom {
///     inner: Arc<ServiceLevelPriorityService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ServiceLevelPriorityService = GenericCrudService<
    ServiceLevelPriority,
    CreateServiceLevelPriorityDto,
    UpdateServiceLevelPriorityDto,
    ServiceLevelPriorityRepository,
>;

// <<< CUSTOM
// END CUSTOM
