//! Application service for WarrantyClaim entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `warranty_claim_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateWarrantyClaimDto, UpdateWarrantyClaimDto};
use crate::domain::entity::WarrantyClaim;
use crate::infrastructure::persistence::WarrantyClaimRepository;

/// Application service for WarrantyClaim entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `warranty_claim_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct WarrantyClaimServiceCustom {
///     inner: Arc<WarrantyClaimService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type WarrantyClaimService = GenericCrudService<
    WarrantyClaim,
    CreateWarrantyClaimDto,
    UpdateWarrantyClaimDto,
    WarrantyClaimRepository,
>;

// <<< CUSTOM
// END CUSTOM
