-- Issue Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the support.issues table.
-- Customize this file to add your initial data.

-- INSERT INTO support.issues (
--     id,
--     company_id,
--     customer_id,
--     subject,
--     description,
--     priority,
--     sla_id,
--     status,
--     agreement_status,
--     opened_at,
--     response_by,
--     resolution_by,
--     first_responded_at,
--     response_breached,
--     resolved_at,
--     paused_at,
--     total_paused_mins,
--     escalated_project_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO support.issues (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

