-- ServiceLevelPriority Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the support.service_level_priorities table.
-- Customize this file to add your initial data.

-- INSERT INTO support.service_level_priorities (
--     id,
--     sla_id,
--     priority,
--     response_time_mins,
--     resolution_time_mins,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO support.service_level_priorities (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

