-- WarrantyClaim Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the support.warranty_claims table.
-- Customize this file to add your initial data.

-- INSERT INTO support.warranty_claims (
--     id,
--     company_id,
--     customer_id,
--     item_id,
--     serial_no,
--     claim_date,
--     warranty_expiry,
--     is_under_warranty,
--     status,
--     issue_id,
--     description,
--     resolution,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO support.warranty_claims (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

