-- Migration: Create warranty_claims table
-- Generated by metaphor-schema

-- Create warranty_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'warranty_status') THEN
        CREATE TYPE warranty_status AS ENUM ('open', 'accepted', 'rejected', 'closed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS support;

CREATE TABLE IF NOT EXISTS support.warranty_claims (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    customer_id UUID,
    item_id UUID NOT NULL,
    serial_no TEXT,
    claim_date TIMESTAMPTZ NOT NULL,
    warranty_expiry TIMESTAMPTZ,
    is_under_warranty BOOLEAN NOT NULL DEFAULT FALSE,
    status warranty_status NOT NULL DEFAULT 'open',
    issue_id UUID,
    description TEXT,
    resolution TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_warranty_claims_company_id_status ON support.warranty_claims (company_id, status);

CREATE INDEX IF NOT EXISTS idx_warranty_claims_customer_id ON support.warranty_claims (customer_id);

CREATE INDEX IF NOT EXISTS idx_warranty_claims_serial_no ON support.warranty_claims (serial_no);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_warranty_claims_metadata_gin ON support.warranty_claims USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_warranty_claims_metadata_deleted_at ON support.warranty_claims ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_warranty_claims_metadata_created_at ON support.warranty_claims ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_warranty_claims_metadata_updated_at ON support.warranty_claims ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION support.warranty_claims_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS warranty_claims_insert_audit ON support.warranty_claims;
CREATE TRIGGER warranty_claims_insert_audit BEFORE INSERT ON support.warranty_claims
    FOR EACH ROW EXECUTE FUNCTION support.warranty_claims_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS warranty_claims_update_audit ON support.warranty_claims;
CREATE TRIGGER warranty_claims_update_audit BEFORE UPDATE ON support.warranty_claims
    FOR EACH ROW EXECUTE FUNCTION support.warranty_claims_audit_timestamp();
