-- Migration: Create service_level_agreements table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS support;

CREATE TABLE IF NOT EXISTS support.service_level_agreements (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_service_level_agreements_company_id_is_active ON support.service_level_agreements (company_id, is_active);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_service_level_agreements_metadata_gin ON support.service_level_agreements USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_service_level_agreements_metadata_deleted_at ON support.service_level_agreements ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_service_level_agreements_metadata_created_at ON support.service_level_agreements ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_service_level_agreements_metadata_updated_at ON support.service_level_agreements ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION support.service_level_agreements_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS service_level_agreements_insert_audit ON support.service_level_agreements;
CREATE TRIGGER service_level_agreements_insert_audit BEFORE INSERT ON support.service_level_agreements
    FOR EACH ROW EXECUTE FUNCTION support.service_level_agreements_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS service_level_agreements_update_audit ON support.service_level_agreements;
CREATE TRIGGER service_level_agreements_update_audit BEFORE UPDATE ON support.service_level_agreements
    FOR EACH ROW EXECUTE FUNCTION support.service_level_agreements_audit_timestamp();
