-- Migration: Create issues table
-- Generated by metaphor-schema

-- Create issue_priority enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'issue_priority') THEN
        CREATE TYPE issue_priority AS ENUM ('low', 'medium', 'high', 'urgent');
    END IF;
END
$$;

-- Create issue_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'issue_status') THEN
        CREATE TYPE issue_status AS ENUM ('open', 'replied', 'on_hold', 'resolved', 'closed');
    END IF;
END
$$;

-- Create agreement_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'agreement_status') THEN
        CREATE TYPE agreement_status AS ENUM ('first_response_due', 'resolution_due', 'fulfilled', 'failed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS support;

CREATE TABLE IF NOT EXISTS support.issues (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    customer_id UUID,
    subject TEXT NOT NULL,
    description TEXT,
    priority issue_priority NOT NULL DEFAULT 'medium',
    sla_id UUID,
    status issue_status NOT NULL DEFAULT 'open',
    agreement_status agreement_status NOT NULL DEFAULT 'first_response_due',
    opened_at TIMESTAMPTZ NOT NULL,
    response_by TIMESTAMPTZ,
    resolution_by TIMESTAMPTZ,
    first_responded_at TIMESTAMPTZ,
    response_breached BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_at TIMESTAMPTZ,
    paused_at TIMESTAMPTZ,
    total_paused_mins INTEGER NOT NULL DEFAULT 0,
    escalated_project_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_issues_company_id_status ON support.issues (company_id, status);

CREATE INDEX IF NOT EXISTS idx_issues_customer_id ON support.issues (customer_id);

CREATE INDEX IF NOT EXISTS idx_issues_company_id_agreement_status ON support.issues (company_id, agreement_status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_issues_metadata_gin ON support.issues USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_issues_metadata_deleted_at ON support.issues ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_issues_metadata_created_at ON support.issues ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_issues_metadata_updated_at ON support.issues ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION support.issues_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS issues_insert_audit ON support.issues;
CREATE TRIGGER issues_insert_audit BEFORE INSERT ON support.issues
    FOR EACH ROW EXECUTE FUNCTION support.issues_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS issues_update_audit ON support.issues;
CREATE TRIGGER issues_update_audit BEFORE UPDATE ON support.issues
    FOR EACH ROW EXECUTE FUNCTION support.issues_audit_timestamp();
