-- Company RLS fence for support module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for support.issues
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE support.issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE support.issues FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS issues_company_isolation ON support.issues;
CREATE POLICY issues_company_isolation ON support.issues
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for support.service_level_agreements
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE support.service_level_agreements ENABLE ROW LEVEL SECURITY;
ALTER TABLE support.service_level_agreements FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_level_agreements_company_isolation ON support.service_level_agreements;
CREATE POLICY service_level_agreements_company_isolation ON support.service_level_agreements
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for support.warranty_claims
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE support.warranty_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE support.warranty_claims FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS warranty_claims_company_isolation ON support.warranty_claims;
CREATE POLICY warranty_claims_company_isolation ON support.warranty_claims
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

