-- Audit Triggers Migration for support module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Issue (support.issues)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION support.issues_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS issues_insert_audit ON support.issues;
CREATE TRIGGER issues_insert_audit BEFORE INSERT ON support.issues
    FOR EACH ROW EXECUTE FUNCTION support.issues_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS issues_update_audit ON support.issues;
CREATE TRIGGER issues_update_audit BEFORE UPDATE ON support.issues
    FOR EACH ROW EXECUTE FUNCTION support.issues_audit_timestamp();

-- ==============================================================================
-- Table: ServiceLevelAgreement (support.service_level_agreements)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION support.service_level_agreements_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS service_level_agreements_insert_audit ON support.service_level_agreements;
CREATE TRIGGER service_level_agreements_insert_audit BEFORE INSERT ON support.service_level_agreements
    FOR EACH ROW EXECUTE FUNCTION support.service_level_agreements_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS service_level_agreements_update_audit ON support.service_level_agreements;
CREATE TRIGGER service_level_agreements_update_audit BEFORE UPDATE ON support.service_level_agreements
    FOR EACH ROW EXECUTE FUNCTION support.service_level_agreements_audit_timestamp();

-- ==============================================================================
-- Table: ServiceLevelPriority (support.service_level_priorities)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION support.service_level_priorities_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS service_level_priorities_insert_audit ON support.service_level_priorities;
CREATE TRIGGER service_level_priorities_insert_audit BEFORE INSERT ON support.service_level_priorities
    FOR EACH ROW EXECUTE FUNCTION support.service_level_priorities_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS service_level_priorities_update_audit ON support.service_level_priorities;
CREATE TRIGGER service_level_priorities_update_audit BEFORE UPDATE ON support.service_level_priorities
    FOR EACH ROW EXECUTE FUNCTION support.service_level_priorities_audit_timestamp();

-- ==============================================================================
-- Table: WarrantyClaim (support.warranty_claims)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION support.warranty_claims_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS warranty_claims_insert_audit ON support.warranty_claims;
CREATE TRIGGER warranty_claims_insert_audit BEFORE INSERT ON support.warranty_claims
    FOR EACH ROW EXECUTE FUNCTION support.warranty_claims_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS warranty_claims_update_audit ON support.warranty_claims;
CREATE TRIGGER warranty_claims_update_audit BEFORE UPDATE ON support.warranty_claims
    FOR EACH ROW EXECUTE FUNCTION support.warranty_claims_audit_timestamp();

