-- Enum types for support module
-- Generated by metaphor-schema

-- Create issue_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'issue_status') THEN
        CREATE TYPE issue_status AS ENUM ('open', 'replied', 'on_hold', 'resolved', 'closed');
    END IF;
END
$$;

-- Create agreement_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'agreement_status') THEN
        CREATE TYPE agreement_status AS ENUM ('first_response_due', 'resolution_due', 'fulfilled', 'failed');
    END IF;
END
$$;

-- Create issue_priority enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'issue_priority') THEN
        CREATE TYPE issue_priority AS ENUM ('low', 'medium', 'high', 'urgent');
    END IF;
END
$$;

-- Create warranty_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'warranty_status') THEN
        CREATE TYPE warranty_status AS ENUM ('open', 'accepted', 'rejected', 'closed');
    END IF;
END
$$;

