-- Migration: Create service_level_priorities table
-- Generated by metaphor-schema

-- Create issue_priority enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'issue_priority') THEN
        CREATE TYPE issue_priority AS ENUM ('low', 'medium', 'high', 'urgent');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS support;

CREATE TABLE IF NOT EXISTS support.service_level_priorities (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    sla_id UUID NOT NULL,
    priority issue_priority NOT NULL,
    response_time_mins INTEGER NOT NULL,
    resolution_time_mins INTEGER NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_service_level_priorities_sla_id_priority ON support.service_level_priorities (sla_id, priority);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_service_level_priorities_metadata_gin ON support.service_level_priorities USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_service_level_priorities_metadata_deleted_at ON support.service_level_priorities ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_service_level_priorities_metadata_created_at ON support.service_level_priorities ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_service_level_priorities_metadata_updated_at ON support.service_level_priorities ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION support.service_level_priorities_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS service_level_priorities_insert_audit ON support.service_level_priorities;
CREATE TRIGGER service_level_priorities_insert_audit BEFORE INSERT ON support.service_level_priorities
    FOR EACH ROW EXECUTE FUNCTION support.service_level_priorities_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS service_level_priorities_update_audit ON support.service_level_priorities;
CREATE TRIGGER service_level_priorities_update_audit BEFORE UPDATE ON support.service_level_priorities
    FOR EACH ROW EXECUTE FUNCTION support.service_level_priorities_audit_timestamp();
