//! Domain events for Issue entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Issue;

/// Domain events for Issue — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Issue>)` variant.
pub type IssueEvent = CrudEvent<Issue>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Issue events.
pub type IssueEventPublisher = Arc<dyn CrudEventPublisher<Issue> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopIssueEventPublisher = NoOpCrudEventPublisher<Issue>;
