//! Event handler trait for Issue events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::IssueEvent;

/// Event handler for Issue events.
/// Implement this trait to react to Issue lifecycle events.
pub trait IssueEventHandler: EventHandler<IssueEvent> {}
