//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod issue_event_handlers;
pub mod issue_events;
pub mod service_level_agreement_event_handlers;
pub mod service_level_agreement_events;
pub mod service_level_priority_event_handlers;
pub mod service_level_priority_events;
pub mod warranty_claim_event_handlers;
pub mod warranty_claim_events;

pub use issue_event_handlers::IssueEventHandler;
pub use issue_events::{IssueEvent, IssueEventPublisher, NoopIssueEventPublisher};
pub use service_level_agreement_event_handlers::ServiceLevelAgreementEventHandler;
pub use service_level_agreement_events::{
    NoopServiceLevelAgreementEventPublisher, ServiceLevelAgreementEvent,
    ServiceLevelAgreementEventPublisher,
};
pub use service_level_priority_event_handlers::ServiceLevelPriorityEventHandler;
pub use service_level_priority_events::{
    NoopServiceLevelPriorityEventPublisher, ServiceLevelPriorityEvent,
    ServiceLevelPriorityEventPublisher,
};
pub use warranty_claim_event_handlers::WarrantyClaimEventHandler;
pub use warranty_claim_events::{
    NoopWarrantyClaimEventPublisher, WarrantyClaimEvent, WarrantyClaimEventPublisher,
};

// <<< CUSTOM
// END CUSTOM
