//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod issue_events;
pub mod issue_event_handlers;
pub mod service_level_agreement_events;
pub mod service_level_agreement_event_handlers;
pub mod service_level_priority_events;
pub mod service_level_priority_event_handlers;
pub mod warranty_claim_events;
pub mod warranty_claim_event_handlers;

pub use issue_events::{IssueEvent, IssueEventPublisher, NoopIssueEventPublisher};
pub use issue_event_handlers::IssueEventHandler;
pub use service_level_agreement_events::{ServiceLevelAgreementEvent, ServiceLevelAgreementEventPublisher, NoopServiceLevelAgreementEventPublisher};
pub use service_level_agreement_event_handlers::ServiceLevelAgreementEventHandler;
pub use service_level_priority_events::{ServiceLevelPriorityEvent, ServiceLevelPriorityEventPublisher, NoopServiceLevelPriorityEventPublisher};
pub use service_level_priority_event_handlers::ServiceLevelPriorityEventHandler;
pub use warranty_claim_events::{WarrantyClaimEvent, WarrantyClaimEventPublisher, NoopWarrantyClaimEventPublisher};
pub use warranty_claim_event_handlers::WarrantyClaimEventHandler;

// <<< CUSTOM
// END CUSTOM
