//! Domain events for ServiceLevelPriority entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ServiceLevelPriority;

/// Domain events for ServiceLevelPriority — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ServiceLevelPriority>)` variant.
pub type ServiceLevelPriorityEvent = CrudEvent<ServiceLevelPriority>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ServiceLevelPriority events.
pub type ServiceLevelPriorityEventPublisher = Arc<dyn CrudEventPublisher<ServiceLevelPriority> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopServiceLevelPriorityEventPublisher = NoOpCrudEventPublisher<ServiceLevelPriority>;
