//! Event handler trait for ServiceLevelPriority events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::ServiceLevelPriorityEvent;
use backbone_messaging::EventHandler;

/// Event handler for ServiceLevelPriority events.
/// Implement this trait to react to ServiceLevelPriority lifecycle events.
pub trait ServiceLevelPriorityEventHandler: EventHandler<ServiceLevelPriorityEvent> {}
