//! Event handler trait for ServiceLevelPriority events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ServiceLevelPriorityEvent;

/// Event handler for ServiceLevelPriority events.
/// Implement this trait to react to ServiceLevelPriority lifecycle events.
pub trait ServiceLevelPriorityEventHandler: EventHandler<ServiceLevelPriorityEvent> {}
