//! Domain events for ServiceLevelAgreement entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ServiceLevelAgreement;

/// Domain events for ServiceLevelAgreement — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ServiceLevelAgreement>)` variant.
pub type ServiceLevelAgreementEvent = CrudEvent<ServiceLevelAgreement>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ServiceLevelAgreement events.
pub type ServiceLevelAgreementEventPublisher = Arc<dyn CrudEventPublisher<ServiceLevelAgreement> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopServiceLevelAgreementEventPublisher = NoOpCrudEventPublisher<ServiceLevelAgreement>;
