//! Event handler trait for ServiceLevelAgreement events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ServiceLevelAgreementEvent;

/// Event handler for ServiceLevelAgreement events.
/// Implement this trait to react to ServiceLevelAgreement lifecycle events.
pub trait ServiceLevelAgreementEventHandler: EventHandler<ServiceLevelAgreementEvent> {}
