//! Event handler trait for WarrantyClaim events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::WarrantyClaimEvent;

/// Event handler for WarrantyClaim events.
/// Implement this trait to react to WarrantyClaim lifecycle events.
pub trait WarrantyClaimEventHandler: EventHandler<WarrantyClaimEvent> {}
