//! Domain events for WarrantyClaim entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::WarrantyClaim;

/// Domain events for WarrantyClaim — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<WarrantyClaim>)` variant.
pub type WarrantyClaimEvent = CrudEvent<WarrantyClaim>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for WarrantyClaim events.
pub type WarrantyClaimEventPublisher = Arc<dyn CrudEventPublisher<WarrantyClaim> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopWarrantyClaimEventPublisher = NoOpCrudEventPublisher<WarrantyClaim>;
