//! Event subscriber type aliases for Support module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::IssueEvent;
use crate::domain::event::ServiceLevelAgreementEvent;
use crate::domain::event::ServiceLevelPriorityEvent;
use crate::domain::event::WarrantyClaimEvent;

/// Subscriber for Issue events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type IssueEventSubscriber = GenericEventSubscriber<IssueEvent>;

/// Subscriber for ServiceLevelAgreement events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ServiceLevelAgreementEventSubscriber = GenericEventSubscriber<ServiceLevelAgreementEvent>;

/// Subscriber for ServiceLevelPriority events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ServiceLevelPriorityEventSubscriber = GenericEventSubscriber<ServiceLevelPriorityEvent>;

/// Subscriber for WarrantyClaim events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type WarrantyClaimEventSubscriber = GenericEventSubscriber<WarrantyClaimEvent>;

// <<< CUSTOM
// END CUSTOM
