//! ServiceLevelAgreement seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ServiceLevelAgreement data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SERVICELEVELAGREEMENT SEEDER
// ============================================================================

/// Seeder for service_level_agreement
pub struct SeedServiceLevelAgreementSeeder;

impl SeedServiceLevelAgreementSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedServiceLevelAgreementSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedServiceLevelAgreementSeeder {
    fn name(&self) -> &'static str {
        "SeedServiceLevelAgreementSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if support.service_level_agreements table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM support.service_level_agreements")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/service_level_agreement_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM support.service_level_agreements")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

