//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod issue_repository;
pub mod service_level_agreement_repository;
pub mod service_level_priority_repository;
pub mod warranty_claim_repository;

// Re-exports
pub use issue_repository::{
    IssueRepository,
    IssuePaginationParams,
    IssuePaginatedResult,
    IssueFilter,
};
pub use service_level_agreement_repository::{
    ServiceLevelAgreementRepository,
    ServiceLevelAgreementPaginationParams,
    ServiceLevelAgreementPaginatedResult,
    ServiceLevelAgreementFilter,
};
pub use service_level_priority_repository::{
    ServiceLevelPriorityRepository,
    ServiceLevelPriorityPaginationParams,
    ServiceLevelPriorityPaginatedResult,
    ServiceLevelPriorityFilter,
};
pub use warranty_claim_repository::{
    WarrantyClaimRepository,
    WarrantyClaimPaginationParams,
    WarrantyClaimPaginatedResult,
    WarrantyClaimFilter,
};
