//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.

pub mod issue_repository;
pub mod service_level_agreement_repository;
pub mod service_level_priority_repository;
pub mod warranty_claim_repository;

// Re-exports
pub use issue_repository::{
    IssueFilter, IssuePaginatedResult, IssuePaginationParams, IssueRepository,
};
pub use service_level_agreement_repository::{
    ServiceLevelAgreementFilter, ServiceLevelAgreementPaginatedResult,
    ServiceLevelAgreementPaginationParams, ServiceLevelAgreementRepository,
};
pub use service_level_priority_repository::{
    ServiceLevelPriorityFilter, ServiceLevelPriorityPaginatedResult,
    ServiceLevelPriorityPaginationParams, ServiceLevelPriorityRepository,
};
pub use warranty_claim_repository::{
    WarrantyClaimFilter, WarrantyClaimPaginatedResult, WarrantyClaimPaginationParams,
    WarrantyClaimRepository,
};
