//! Repository trait for ServiceLevelAgreement aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ServiceLevelAgreement aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ServiceLevelAgreement;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ServiceLevelAgreementPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ServiceLevelAgreementPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ServiceLevelAgreementPaginatedResult {
    pub data: Vec<ServiceLevelAgreement>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ServiceLevelAgreementFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub is_default: Option<bool>,
    pub is_active: Option<bool>,
}

impl ServiceLevelAgreementFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.is_default.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for ServiceLevelAgreement aggregate
///
/// This trait defines the persistence contract for ServiceLevelAgreement entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ServiceLevelAgreementRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new service_level_agreement entity
    async fn save(&self, entity: &ServiceLevelAgreement) -> Result<ServiceLevelAgreement>;

    /// Find service_level_agreement by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ServiceLevelAgreement>>;

    /// Find all service_level_agreement entities
    async fn find_all(&self) -> Result<Vec<ServiceLevelAgreement>>;

    /// Update service_level_agreement by ID
    async fn update(&self, id: &str, entity: &ServiceLevelAgreement) -> Result<Option<ServiceLevelAgreement>>;

    /// Delete service_level_agreement by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List service_level_agreement with pagination
    async fn list(&self, params: ServiceLevelAgreementPaginationParams) -> Result<ServiceLevelAgreementPaginatedResult>;

    /// List service_level_agreement with pagination and filters
    async fn list_with_filters(&self, params: ServiceLevelAgreementPaginationParams, filters: ServiceLevelAgreementFilter) -> Result<ServiceLevelAgreementPaginatedResult>;

    /// Count all service_level_agreement entities
    async fn count(&self) -> Result<u64>;

    /// Count service_level_agreement entities matching filters
    async fn count_with_filters(&self, filters: ServiceLevelAgreementFilter) -> Result<u64>;

    /// Check if service_level_agreement exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete service_level_agreement by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted service_level_agreement by ID
    async fn restore(&self, id: &str) -> Result<Option<ServiceLevelAgreement>>;

    /// List soft-deleted service_level_agreement entities
    async fn list_deleted(&self, params: ServiceLevelAgreementPaginationParams) -> Result<ServiceLevelAgreementPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save service_level_agreement entities
    async fn bulk_save(&self, entities: &[ServiceLevelAgreement]) -> Result<Vec<ServiceLevelAgreement>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
