//! Repository trait for ServiceLevelPriority aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ServiceLevelPriority aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{ServiceLevelPriority, IssuePriority};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ServiceLevelPriorityPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ServiceLevelPriorityPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ServiceLevelPriorityPaginatedResult {
    pub data: Vec<ServiceLevelPriority>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ServiceLevelPriorityFilter {
    pub sla_id: Option<Uuid>,
    pub priority: Option<IssuePriority>,
}

impl ServiceLevelPriorityFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.sla_id.is_some() || self.priority.is_some()
    }
}

/// Repository trait for ServiceLevelPriority aggregate
///
/// This trait defines the persistence contract for ServiceLevelPriority entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ServiceLevelPriorityRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new service_level_priority entity
    async fn save(&self, entity: &ServiceLevelPriority) -> Result<ServiceLevelPriority>;

    /// Find service_level_priority by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ServiceLevelPriority>>;

    /// Find all service_level_priority entities
    async fn find_all(&self) -> Result<Vec<ServiceLevelPriority>>;

    /// Update service_level_priority by ID
    async fn update(&self, id: &str, entity: &ServiceLevelPriority) -> Result<Option<ServiceLevelPriority>>;

    /// Delete service_level_priority by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List service_level_priority with pagination
    async fn list(&self, params: ServiceLevelPriorityPaginationParams) -> Result<ServiceLevelPriorityPaginatedResult>;

    /// List service_level_priority with pagination and filters
    async fn list_with_filters(&self, params: ServiceLevelPriorityPaginationParams, filters: ServiceLevelPriorityFilter) -> Result<ServiceLevelPriorityPaginatedResult>;

    /// Count all service_level_priority entities
    async fn count(&self) -> Result<u64>;

    /// Count service_level_priority entities matching filters
    async fn count_with_filters(&self, filters: ServiceLevelPriorityFilter) -> Result<u64>;

    /// Check if service_level_priority exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete service_level_priority by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted service_level_priority by ID
    async fn restore(&self, id: &str) -> Result<Option<ServiceLevelPriority>>;

    /// List soft-deleted service_level_priority entities
    async fn list_deleted(&self, params: ServiceLevelPriorityPaginationParams) -> Result<ServiceLevelPriorityPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save service_level_priority entities
    async fn bulk_save(&self, entities: &[ServiceLevelPriority]) -> Result<Vec<ServiceLevelPriority>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
