//! Repository trait for WarrantyClaim aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the WarrantyClaim aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{WarrantyClaim, WarrantyStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WarrantyClaimPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl WarrantyClaimPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct WarrantyClaimPaginatedResult {
    pub data: Vec<WarrantyClaim>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct WarrantyClaimFilter {
    pub company_id: Option<Uuid>,
    pub customer_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub serial_no: Option<String>,
    pub is_under_warranty: Option<bool>,
    pub status: Option<WarrantyStatus>,
    pub issue_id: Option<Uuid>,
    pub description: Option<String>,
    pub resolution: Option<String>,
}

impl WarrantyClaimFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.customer_id.is_some() || self.item_id.is_some() || self.serial_no.is_some() || self.is_under_warranty.is_some() || self.status.is_some() || self.issue_id.is_some() || self.description.is_some() || self.resolution.is_some()
    }
}

/// Repository trait for WarrantyClaim aggregate
///
/// This trait defines the persistence contract for WarrantyClaim entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait WarrantyClaimRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new warranty_claim entity
    async fn save(&self, entity: &WarrantyClaim) -> Result<WarrantyClaim>;

    /// Find warranty_claim by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<WarrantyClaim>>;

    /// Find all warranty_claim entities
    async fn find_all(&self) -> Result<Vec<WarrantyClaim>>;

    /// Update warranty_claim by ID
    async fn update(&self, id: &str, entity: &WarrantyClaim) -> Result<Option<WarrantyClaim>>;

    /// Delete warranty_claim by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List warranty_claim with pagination
    async fn list(&self, params: WarrantyClaimPaginationParams) -> Result<WarrantyClaimPaginatedResult>;

    /// List warranty_claim with pagination and filters
    async fn list_with_filters(&self, params: WarrantyClaimPaginationParams, filters: WarrantyClaimFilter) -> Result<WarrantyClaimPaginatedResult>;

    /// Count all warranty_claim entities
    async fn count(&self) -> Result<u64>;

    /// Count warranty_claim entities matching filters
    async fn count_with_filters(&self, filters: WarrantyClaimFilter) -> Result<u64>;

    /// Check if warranty_claim exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete warranty_claim by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted warranty_claim by ID
    async fn restore(&self, id: &str) -> Result<Option<WarrantyClaim>>;

    /// List soft-deleted warranty_claim entities
    async fn list_deleted(&self, params: WarrantyClaimPaginationParams) -> Result<WarrantyClaimPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save warranty_claim entities
    async fn bulk_save(&self, entities: &[WarrantyClaim]) -> Result<Vec<WarrantyClaim>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
