//! Repository for Issue entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Issue, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Issue;

/// Table name for Issue entities
pub const TABLE_NAME: &str = "support.issues";

/// Repository for Issue entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct IssueRepository(
    backbone_orm::GenericCrudRepository<Issue, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for IssueRepository {
    type Target = backbone_orm::GenericCrudRepository<Issue, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl IssueRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(IssueRepository, Issue, soft_delete);
