//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod issue_repository;
mod service_level_agreement_repository;
mod service_level_priority_repository;
mod warranty_claim_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use issue_repository::IssueRepository;
pub use service_level_agreement_repository::ServiceLevelAgreementRepository;
pub use service_level_priority_repository::ServiceLevelPriorityRepository;
pub use warranty_claim_repository::WarrantyClaimRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// The hand-written support SQL's parameter/projection types (see the repositories declared
// `user_owned` in metaphor.codegen.yaml).
pub use issue_repository::{EscalationCandidateRow, IssueStateRow, NewIssueRow, PausedIssueRow};
pub use service_level_agreement_repository::NewSlaRow;
pub use service_level_priority_repository::{NewSlaPriorityRow, SlaTargetRow};
pub use warranty_claim_repository::NewWarrantyClaimRow;
// END CUSTOM