//! Repository for ServiceLevelPriority entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ServiceLevelPriority, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ServiceLevelPriority;

/// Table name for ServiceLevelPriority entities
pub const TABLE_NAME: &str = "support.service_level_priorities";

/// Repository for ServiceLevelPriority entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ServiceLevelPriorityRepository(
    backbone_orm::GenericCrudRepository<ServiceLevelPriority, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ServiceLevelPriorityRepository {
    type Target = backbone_orm::GenericCrudRepository<ServiceLevelPriority, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ServiceLevelPriorityRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ServiceLevelPriorityRepository, ServiceLevelPriority, soft_delete);
