//! Repository for ServiceLevelAgreement entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written SLA SQL (4-layer rule: services orchestrate, repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ServiceLevelAgreement, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::ServiceLevelAgreement;

/// Table name for ServiceLevelAgreement entities
pub const TABLE_NAME: &str = "support.service_level_agreements";

/// Repository for ServiceLevelAgreement entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ServiceLevelAgreementRepository(
    backbone_orm::GenericCrudRepository<ServiceLevelAgreement, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ServiceLevelAgreementRepository {
    type Target = backbone_orm::GenericCrudRepository<ServiceLevelAgreement, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ServiceLevelAgreementRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an SLA definition writes.
///
/// Mirrors the raw column shape rather than the `ServiceLevelAgreement` entity — the write service
/// composes it from its `NewSla` DTO and never hands a generated entity to the SQL.
pub struct NewSlaRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub name: &'a str,
    pub is_default: bool,
}

/// Hand-written ServiceLevelAgreement SQL. Lives here (not in the write service) per the module's
/// 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl ServiceLevelAgreementRepository {
    /// Insert the SLA header. Takes the CALLER'S connection so the header and its per-priority target
    /// rows commit as one unit. The caller binds the company on that connection (`bind_company_on`)
    /// before calling — don't re-bind here.
    pub async fn insert_sla(
        &self,
        conn: &mut sqlx::PgConnection,
        s: &NewSlaRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO support.service_level_agreements (id, company_id, name, is_default, is_active)
               VALUES ($1,$2,$3,$4,true)"#,
        )
        .bind(s.id).bind(s.company_id).bind(s.name).bind(s.is_default)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// The company's default active SLA, if it has one — the fallback when a ticket is raised without an
    /// explicit SLA.
    ///
    /// A read outside any transaction: takes the pool and runs `fetch_optional_scalar_scoped` so the RLS
    /// fence (ADR-0008) applies. The explicit `company_id = $1` filter stays as defense-in-depth. The
    /// caller wraps this in `with_company_scope(Some(company))`.
    pub async fn find_default_id(
        &self,
        pool: &PgPool,
        company_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                r#"SELECT id FROM support.service_level_agreements
                   WHERE company_id=$1 AND is_default=true AND is_active=true
                     AND (metadata->>'deleted_at') IS NULL LIMIT 1"#,
            )
            .bind(company_id),
        )
        .await
    }
}

backbone_core::impl_crud_repository!(ServiceLevelAgreementRepository, ServiceLevelAgreement, soft_delete);
