//! Repository for WarrantyClaim entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<WarrantyClaim, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::WarrantyClaim;

/// Table name for WarrantyClaim entities
pub const TABLE_NAME: &str = "support.warranty_claims";

/// Repository for WarrantyClaim entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct WarrantyClaimRepository(
    backbone_orm::GenericCrudRepository<WarrantyClaim, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for WarrantyClaimRepository {
    type Target = backbone_orm::GenericCrudRepository<WarrantyClaim, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl WarrantyClaimRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(WarrantyClaimRepository, WarrantyClaim, soft_delete);
