//! Repository for WarrantyClaim entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written WarrantyClaim SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<WarrantyClaim, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::{DateTime, Utc};
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::WarrantyClaim;

/// Table name for WarrantyClaim entities
pub const TABLE_NAME: &str = "support.warranty_claims";

/// Repository for WarrantyClaim entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct WarrantyClaimRepository(
    backbone_orm::GenericCrudRepository<WarrantyClaim, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for WarrantyClaimRepository {
    type Target = backbone_orm::GenericCrudRepository<WarrantyClaim, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl WarrantyClaimRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a filed warranty claim writes.
///
/// Mirrors the raw column shape rather than the `WarrantyClaim` entity. Coverage
/// (`is_under_warranty`) is computed by the caller at file time and stored, not re-derived here.
pub struct NewWarrantyClaimRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub customer_id: Option<Uuid>,
    pub item_id: Uuid,
    pub serial_no: Option<&'a str>,
    pub claim_date: DateTime<Utc>,
    pub warranty_expiry: Option<DateTime<Utc>>,
    pub is_under_warranty: bool,
    pub issue_id: Option<Uuid>,
    pub description: Option<&'a str>,
}

/// Hand-written WarrantyClaim SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl WarrantyClaimRepository {
    /// File a warranty claim.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` — the company is
    /// on the DTO, and that scope is what satisfies the INSERT's WITH CHECK fence.
    pub async fn insert_claim(&self, pool: &PgPool, c: &NewWarrantyClaimRow<'_>) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO support.warranty_claims
                     (id, company_id, customer_id, item_id, serial_no, claim_date, warranty_expiry,
                      is_under_warranty, status, issue_id, description)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'open'::warranty_status,$9,$10)"#,
            )
            .bind(c.id).bind(c.company_id).bind(c.customer_id).bind(c.item_id).bind(c.serial_no)
            .bind(c.claim_date).bind(c.warranty_expiry).bind(c.is_under_warranty).bind(c.issue_id)
            .bind(c.description),
        )
        .await?;
        Ok(())
    }

    /// Adjudicate an open claim. `status` is bound as a free string and cast at the DB
    /// (`$2::warranty_status`). Returns rows affected (0 = not an open claim in scope).
    ///
    /// ID-only: no company argument. Runs `execute_scoped`, so it rides a connection carrying the
    /// caller's `app.company_id` and another company's claim simply is not updated. A non-request caller
    /// (event/job) must wrap this in `with_company_scope(Some(company_id))` or it fails closed.
    pub async fn adjudicate(
        &self,
        pool: &PgPool,
        claim_id: Uuid,
        status: &str,
        resolution: Option<&str>,
    ) -> Result<u64, sqlx::Error> {
        let moved = company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE support.warranty_claims SET status=$2::warranty_status, resolution=$3
                   WHERE id=$1 AND status='open'::warranty_status AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(claim_id).bind(status).bind(resolution),
        )
        .await?;
        Ok(moved.rows_affected())
    }
}

backbone_core::impl_crud_repository!(WarrantyClaimRepository, WarrantyClaim, soft_delete);
