//! Validator for Issue entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Issue>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::Issue;

/// Validator type alias for Issue entities.
pub type IssueValidator = EntityValidator<Issue>;

/// Build a validator for Issue with all schema-defined field rules.
pub fn issue_validator() -> IssueValidator {
    EntityValidator::new()
        .rule(RequiredString::new("subject", |e: &Issue| &e.subject))
        .rule(OptionalNotBlank::new("description", |e: &Issue| e.description.as_deref()))
        .rule(NonNegative::new("total_paused_mins", |e: &Issue| e.total_paused_mins as i64))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
