//! Validator for WarrantyClaim entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<WarrantyClaim>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::WarrantyClaim;

/// Validator type alias for WarrantyClaim entities.
pub type WarrantyClaimValidator = EntityValidator<WarrantyClaim>;

/// Build a validator for WarrantyClaim with all schema-defined field rules.
pub fn warranty_claim_validator() -> WarrantyClaimValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("serial_no", |e: &WarrantyClaim| e.serial_no.as_deref()))
        .rule(OptionalNotBlank::new("description", |e: &WarrantyClaim| e.description.as_deref()))
        .rule(OptionalNotBlank::new("resolution", |e: &WarrantyClaim| e.resolution.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
