//! Auth configuration for Issue handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Issue>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::IssueService;
use crate::domain::entity::Issue;

/// Permission string constants for Issue operations.
pub mod permissions {
    pub const LIST:        &str = "issue:list";
    pub const READ:        &str = "issue:read";
    pub const CREATE:      &str = "issue:create";
    pub const UPDATE:      &str = "issue:update";
    pub const DELETE:      &str = "issue:delete";
    pub const RESTORE:     &str = "issue:restore";
    pub const TRASH:       &str = "issue:trash";
    pub const EMPTY_TRASH: &str = "issue:empty_trash";
    pub const BULK_CREATE: &str = "issue:bulk_create";
    pub const UPSERT:      &str = "issue:upsert";
}

/// Resource policy for Issue — maps CRUD actions to permission strings.
pub struct IssuePolicy;

#[async_trait]
impl ResourcePolicy<Issue> for IssuePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Issue,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Issue handlers.
///
/// Wraps `IssueService` and checks `IssuePolicy` before delegating.
pub type IssueGuard = PermissionGuard<Issue>;

/// Service-integrated permission guard for Issue (for use in generated handlers).
pub type IssueServiceGuard = ServicePermissionGuard<Issue, IssueService, IssuePolicy>;

// <<< CUSTOM
// END CUSTOM
