//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod issue_auth;
pub mod service_level_agreement_auth;
pub mod service_level_priority_auth;
pub mod warranty_claim_auth;

pub use issue_auth::{IssuePolicy, IssueGuard, IssueServiceGuard};
pub use service_level_agreement_auth::{ServiceLevelAgreementPolicy, ServiceLevelAgreementGuard, ServiceLevelAgreementServiceGuard};
pub use service_level_priority_auth::{ServiceLevelPriorityPolicy, ServiceLevelPriorityGuard, ServiceLevelPriorityServiceGuard};
pub use warranty_claim_auth::{WarrantyClaimPolicy, WarrantyClaimGuard, WarrantyClaimServiceGuard};

// <<< CUSTOM
// END CUSTOM
