//! Auth configuration for ServiceLevelPriority handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ServiceLevelPriority>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ServiceLevelPriorityService;
use crate::domain::entity::ServiceLevelPriority;

/// Permission string constants for ServiceLevelPriority operations.
pub mod permissions {
    pub const LIST:        &str = "service_level_priority:list";
    pub const READ:        &str = "service_level_priority:read";
    pub const CREATE:      &str = "service_level_priority:create";
    pub const UPDATE:      &str = "service_level_priority:update";
    pub const DELETE:      &str = "service_level_priority:delete";
    pub const RESTORE:     &str = "service_level_priority:restore";
    pub const TRASH:       &str = "service_level_priority:trash";
    pub const EMPTY_TRASH: &str = "service_level_priority:empty_trash";
    pub const BULK_CREATE: &str = "service_level_priority:bulk_create";
    pub const UPSERT:      &str = "service_level_priority:upsert";
}

/// Resource policy for ServiceLevelPriority — maps CRUD actions to permission strings.
pub struct ServiceLevelPriorityPolicy;

#[async_trait]
impl ResourcePolicy<ServiceLevelPriority> for ServiceLevelPriorityPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ServiceLevelPriority,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ServiceLevelPriority handlers.
///
/// Wraps `ServiceLevelPriorityService` and checks `ServiceLevelPriorityPolicy` before delegating.
pub type ServiceLevelPriorityGuard = PermissionGuard<ServiceLevelPriority>;

/// Service-integrated permission guard for ServiceLevelPriority (for use in generated handlers).
pub type ServiceLevelPriorityServiceGuard = ServicePermissionGuard<ServiceLevelPriority, ServiceLevelPriorityService, ServiceLevelPriorityPolicy>;

// <<< CUSTOM
// END CUSTOM
