//! Auth configuration for WarrantyClaim handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<WarrantyClaim>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::WarrantyClaimService;
use crate::domain::entity::WarrantyClaim;

/// Permission string constants for WarrantyClaim operations.
pub mod permissions {
    pub const LIST:        &str = "warranty_claim:list";
    pub const READ:        &str = "warranty_claim:read";
    pub const CREATE:      &str = "warranty_claim:create";
    pub const UPDATE:      &str = "warranty_claim:update";
    pub const DELETE:      &str = "warranty_claim:delete";
    pub const RESTORE:     &str = "warranty_claim:restore";
    pub const TRASH:       &str = "warranty_claim:trash";
    pub const EMPTY_TRASH: &str = "warranty_claim:empty_trash";
    pub const BULK_CREATE: &str = "warranty_claim:bulk_create";
    pub const UPSERT:      &str = "warranty_claim:upsert";
}

/// Resource policy for WarrantyClaim — maps CRUD actions to permission strings.
pub struct WarrantyClaimPolicy;

#[async_trait]
impl ResourcePolicy<WarrantyClaim> for WarrantyClaimPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &WarrantyClaim,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for WarrantyClaim handlers.
///
/// Wraps `WarrantyClaimService` and checks `WarrantyClaimPolicy` before delegating.
pub type WarrantyClaimGuard = PermissionGuard<WarrantyClaim>;

/// Service-integrated permission guard for WarrantyClaim (for use in generated handlers).
pub type WarrantyClaimServiceGuard = ServicePermissionGuard<WarrantyClaim, WarrantyClaimService, WarrantyClaimPolicy>;

// <<< CUSTOM
// END CUSTOM
