//! Issue API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Issue CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ISSUE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Issue
pub struct IssueTestData;

impl TestDataGenerator for IssueTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "customer_id": null,
            "subject": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "priority": "low",
            "sla_id": null,
            "status": "open",
            "agreement_status": "first_response_due",
            "opened_at": now,
            "response_by": null,
            "resolution_by": null,
            "first_responded_at": now,
            "response_breached": false,
            "resolved_at": now,
            "paused_at": now,
            "total_paused_mins": 1,
            "escalated_project_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "customer_id": null,
            "subject": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "priority": "low",
            "sla_id": null,
            "status": "open",
            "agreement_status": "first_response_due",
            "opened_at": now,
            "response_by": null,
            "resolution_by": null,
            "first_responded_at": now,
            "response_breached": false,
            "resolved_at": now,
            "paused_at": now,
            "total_paused_mins": 1,
            "escalated_project_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ISSUE API TEST
// ============================================================================

/// Issue API test suite
pub struct IssueApiTest {
    inner: GenericCrudTest<IssueTestData>,
}

impl IssueApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/issues", "Issue");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, IssueTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for IssueApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_issue_crud() {
        let mut test = IssueApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Issue specific tests here
// <<< CUSTOM TESTS END >>>
