//! ServiceLevelPriority API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ServiceLevelPriority CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SERVICELEVELPRIORITY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ServiceLevelPriority
pub struct ServiceLevelPriorityTestData;

impl TestDataGenerator for ServiceLevelPriorityTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "sla_id": Uuid::new_v4().to_string(),
            "priority": "low",
            "response_time_mins": 1,
            "resolution_time_mins": 1,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "sla_id": Uuid::new_v4().to_string(),
            "priority": "low",
            "response_time_mins": 1,
            "resolution_time_mins": 1,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/service_level_agreements", &super::service_level_agreement_api_test::ServiceLevelAgreementTestData).await {
            deps.push(("sla_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// SERVICELEVELPRIORITY API TEST
// ============================================================================

/// ServiceLevelPriority API test suite
pub struct ServiceLevelPriorityApiTest {
    inner: GenericCrudTest<ServiceLevelPriorityTestData>,
}

impl ServiceLevelPriorityApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/service_level_priorities", "ServiceLevelPriority");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ServiceLevelPriorityTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ServiceLevelPriorityApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_service_level_priority_crud() {
        let mut test = ServiceLevelPriorityApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ServiceLevelPriority specific tests here
// <<< CUSTOM TESTS END >>>
