//! Support Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Support exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use support::exports::{IssueDto, SupportQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `IssueDto` - Data transfer object for Issue
/// - `IssueSummary` - Summary view of Issue
/// - `IssueId` - Type-safe ID wrapper
/// - `ServiceLevelAgreementDto` - Data transfer object for ServiceLevelAgreement
/// - `ServiceLevelAgreementSummary` - Summary view of ServiceLevelAgreement
/// - `ServiceLevelAgreementId` - Type-safe ID wrapper
/// - `ServiceLevelPriorityDto` - Data transfer object for ServiceLevelPriority
/// - `ServiceLevelPrioritySummary` - Summary view of ServiceLevelPriority
/// - `ServiceLevelPriorityId` - Type-safe ID wrapper
/// - `WarrantyClaimDto` - Data transfer object for WarrantyClaim
/// - `WarrantyClaimSummary` - Summary view of WarrantyClaim
/// - `WarrantyClaimId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `SupportQueryService` - Read-only queries
///
/// ## Public Events
/// - `IssueCreatedEvent` - Published when Issue is created
/// - `IssueUpdatedEvent` - Published when Issue is updated
/// - `IssueDeletedEvent` - Published when Issue is deleted
/// - `ServiceLevelAgreementCreatedEvent` - Published when ServiceLevelAgreement is created
/// - `ServiceLevelAgreementUpdatedEvent` - Published when ServiceLevelAgreement is updated
/// - `ServiceLevelAgreementDeletedEvent` - Published when ServiceLevelAgreement is deleted
/// - `ServiceLevelPriorityCreatedEvent` - Published when ServiceLevelPriority is created
/// - `ServiceLevelPriorityUpdatedEvent` - Published when ServiceLevelPriority is updated
/// - `ServiceLevelPriorityDeletedEvent` - Published when ServiceLevelPriority is deleted
/// - `WarrantyClaimCreatedEvent` - Published when WarrantyClaim is created
/// - `WarrantyClaimUpdatedEvent` - Published when WarrantyClaim is updated
/// - `WarrantyClaimDeletedEvent` - Published when WarrantyClaim is deleted
pub struct ExportSummary;
