//! Public services for Support module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Support module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait SupportQueryService: Send + Sync {
    /// Get Issue by ID
    async fn get_issue(&self, id: IssueId) -> Result<Option<IssueDto>>;

    /// Get Issue summary by ID
    async fn get_issue_summary(&self, id: IssueId) -> Result<Option<IssueSummary>>;

    /// Check if Issue exists
    async fn issue_exists(&self, id: IssueId) -> Result<bool>;

    /// Get ServiceLevelAgreement by ID
    async fn get_service_level_agreement(&self, id: ServiceLevelAgreementId) -> Result<Option<ServiceLevelAgreementDto>>;

    /// Get ServiceLevelAgreement summary by ID
    async fn get_service_level_agreement_summary(&self, id: ServiceLevelAgreementId) -> Result<Option<ServiceLevelAgreementSummary>>;

    /// Check if ServiceLevelAgreement exists
    async fn service_level_agreement_exists(&self, id: ServiceLevelAgreementId) -> Result<bool>;

    /// Get ServiceLevelPriority by ID
    async fn get_service_level_priority(&self, id: ServiceLevelPriorityId) -> Result<Option<ServiceLevelPriorityDto>>;

    /// Get ServiceLevelPriority summary by ID
    async fn get_service_level_priority_summary(&self, id: ServiceLevelPriorityId) -> Result<Option<ServiceLevelPrioritySummary>>;

    /// Check if ServiceLevelPriority exists
    async fn service_level_priority_exists(&self, id: ServiceLevelPriorityId) -> Result<bool>;

    /// Get WarrantyClaim by ID
    async fn get_warranty_claim(&self, id: WarrantyClaimId) -> Result<Option<WarrantyClaimDto>>;

    /// Get WarrantyClaim summary by ID
    async fn get_warranty_claim_summary(&self, id: WarrantyClaimId) -> Result<Option<WarrantyClaimSummary>>;

    /// Check if WarrantyClaim exists
    async fn warranty_claim_exists(&self, id: WarrantyClaimId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of SupportQueryService
pub struct SupportQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> SupportQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
