//! Public types for Support module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use crate::domain::entity::*;

// ============================================================================
// ISSUE TYPES
// ============================================================================

/// Type-safe ID for Issue
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct IssueId(pub Uuid);

impl IssueId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for IssueId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<IssueId> for Uuid {
    fn from(id: IssueId) -> Self {
        id.0
    }
}

/// Data transfer object for Issue
///
/// This is the public representation of Issue for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IssueDto {
    pub id: IssueId,
    pub company_id: Uuid,
    pub customer_id: Option<Uuid>,
    pub subject: String,
    pub description: Option<String>,
    pub priority: IssuePriority,
    pub sla_id: Option<Uuid>,
    pub status: IssueStatus,
    pub agreement_status: AgreementStatus,
    pub opened_at: DateTime<Utc>,
    pub response_by: Option<DateTime<Utc>>,
    pub resolution_by: Option<DateTime<Utc>>,
    pub first_responded_at: Option<DateTime<Utc>>,
    pub response_breached: bool,
    pub resolved_at: Option<DateTime<Utc>>,
    pub paused_at: Option<DateTime<Utc>>,
    pub total_paused_mins: i32,
    pub escalated_project_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of Issue for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IssueSummary {
    pub id: IssueId,
    pub status: IssueStatus,
}

/// Reference to Issue for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IssueRef {
    pub id: IssueId,
}

// ============================================================================
// SERVICELEVELAGREEMENT TYPES
// ============================================================================

/// Type-safe ID for ServiceLevelAgreement
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ServiceLevelAgreementId(pub Uuid);

impl ServiceLevelAgreementId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ServiceLevelAgreementId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ServiceLevelAgreementId> for Uuid {
    fn from(id: ServiceLevelAgreementId) -> Self {
        id.0
    }
}

/// Data transfer object for ServiceLevelAgreement
///
/// This is the public representation of ServiceLevelAgreement for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceLevelAgreementDto {
    pub id: ServiceLevelAgreementId,
    pub company_id: Uuid,
    pub name: String,
    pub is_default: bool,
    pub is_active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of ServiceLevelAgreement for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceLevelAgreementSummary {
    pub id: ServiceLevelAgreementId,
    pub name: String,
}

/// Reference to ServiceLevelAgreement for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceLevelAgreementRef {
    pub id: ServiceLevelAgreementId,
}

// ============================================================================
// SERVICELEVELPRIORITY TYPES
// ============================================================================

/// Type-safe ID for ServiceLevelPriority
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ServiceLevelPriorityId(pub Uuid);

impl ServiceLevelPriorityId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ServiceLevelPriorityId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ServiceLevelPriorityId> for Uuid {
    fn from(id: ServiceLevelPriorityId) -> Self {
        id.0
    }
}

/// Data transfer object for ServiceLevelPriority
///
/// This is the public representation of ServiceLevelPriority for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceLevelPriorityDto {
    pub id: ServiceLevelPriorityId,
    pub sla_id: Uuid,
    pub priority: IssuePriority,
    pub response_time_mins: i32,
    pub resolution_time_mins: i32,
    pub metadata: serde_json::Value,
}

/// Summary view of ServiceLevelPriority for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceLevelPrioritySummary {
    pub id: ServiceLevelPriorityId,
}

/// Reference to ServiceLevelPriority for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceLevelPriorityRef {
    pub id: ServiceLevelPriorityId,
}

// ============================================================================
// WARRANTYCLAIM TYPES
// ============================================================================

/// Type-safe ID for WarrantyClaim
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct WarrantyClaimId(pub Uuid);

impl WarrantyClaimId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for WarrantyClaimId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<WarrantyClaimId> for Uuid {
    fn from(id: WarrantyClaimId) -> Self {
        id.0
    }
}

/// Data transfer object for WarrantyClaim
///
/// This is the public representation of WarrantyClaim for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WarrantyClaimDto {
    pub id: WarrantyClaimId,
    pub company_id: Uuid,
    pub customer_id: Option<Uuid>,
    pub item_id: Uuid,
    pub serial_no: Option<String>,
    pub claim_date: DateTime<Utc>,
    pub warranty_expiry: Option<DateTime<Utc>>,
    pub is_under_warranty: bool,
    pub status: WarrantyStatus,
    pub issue_id: Option<Uuid>,
    pub description: Option<String>,
    pub resolution: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of WarrantyClaim for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WarrantyClaimSummary {
    pub id: WarrantyClaimId,
    pub status: WarrantyStatus,
}

/// Reference to WarrantyClaim for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WarrantyClaimRef {
    pub id: WarrantyClaimId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
