//! Use case type aliases for Issue aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateIssueDto, UpdateIssueDto};
use crate::application::service::IssueService;
use crate::domain::entity::Issue;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateIssueUseCase = CreateUseCase<Issue, CreateIssueDto, IssueService>;
pub type UpdateIssueUseCase = UpdateUseCase<Issue, UpdateIssueDto, IssueService>;
pub type GetIssueUseCase    = GetUseCase<Issue, IssueService>;
pub type DeleteIssueUseCase = DeleteUseCase<Issue, IssueService>;
pub type ListIssueUseCase   = ListUseCase<Issue, IssueService>;

// <<< CUSTOM
// END CUSTOM
