//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod issue_usecases;
pub mod service_level_agreement_usecases;
pub mod service_level_priority_usecases;
pub mod warranty_claim_usecases;

pub use issue_usecases::{
    CreateIssueUseCase, UpdateIssueUseCase, GetIssueUseCase,
    DeleteIssueUseCase, ListIssueUseCase,
};
pub use service_level_agreement_usecases::{
    CreateServiceLevelAgreementUseCase, UpdateServiceLevelAgreementUseCase, GetServiceLevelAgreementUseCase,
    DeleteServiceLevelAgreementUseCase, ListServiceLevelAgreementUseCase,
};
pub use service_level_priority_usecases::{
    CreateServiceLevelPriorityUseCase, UpdateServiceLevelPriorityUseCase, GetServiceLevelPriorityUseCase,
    DeleteServiceLevelPriorityUseCase, ListServiceLevelPriorityUseCase,
};
pub use warranty_claim_usecases::{
    CreateWarrantyClaimUseCase, UpdateWarrantyClaimUseCase, GetWarrantyClaimUseCase,
    DeleteWarrantyClaimUseCase, ListWarrantyClaimUseCase,
};

// <<< CUSTOM
// END CUSTOM
