//! Use case type aliases for ServiceLevelPriority aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateServiceLevelPriorityDto, UpdateServiceLevelPriorityDto};
use crate::application::service::ServiceLevelPriorityService;
use crate::domain::entity::ServiceLevelPriority;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateServiceLevelPriorityUseCase = CreateUseCase<ServiceLevelPriority, CreateServiceLevelPriorityDto, ServiceLevelPriorityService>;
pub type UpdateServiceLevelPriorityUseCase = UpdateUseCase<ServiceLevelPriority, UpdateServiceLevelPriorityDto, ServiceLevelPriorityService>;
pub type GetServiceLevelPriorityUseCase    = GetUseCase<ServiceLevelPriority, ServiceLevelPriorityService>;
pub type DeleteServiceLevelPriorityUseCase = DeleteUseCase<ServiceLevelPriority, ServiceLevelPriorityService>;
pub type ListServiceLevelPriorityUseCase   = ListUseCase<ServiceLevelPriority, ServiceLevelPriorityService>;

// <<< CUSTOM
// END CUSTOM
