//! Use case type aliases for ServiceLevelAgreement aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateServiceLevelAgreementDto, UpdateServiceLevelAgreementDto};
use crate::application::service::ServiceLevelAgreementService;
use crate::domain::entity::ServiceLevelAgreement;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateServiceLevelAgreementUseCase = CreateUseCase<ServiceLevelAgreement, CreateServiceLevelAgreementDto, ServiceLevelAgreementService>;
pub type UpdateServiceLevelAgreementUseCase = UpdateUseCase<ServiceLevelAgreement, UpdateServiceLevelAgreementDto, ServiceLevelAgreementService>;
pub type GetServiceLevelAgreementUseCase    = GetUseCase<ServiceLevelAgreement, ServiceLevelAgreementService>;
pub type DeleteServiceLevelAgreementUseCase = DeleteUseCase<ServiceLevelAgreement, ServiceLevelAgreementService>;
pub type ListServiceLevelAgreementUseCase   = ListUseCase<ServiceLevelAgreement, ServiceLevelAgreementService>;

// <<< CUSTOM
// END CUSTOM
