//! Use case type aliases for WarrantyClaim aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateWarrantyClaimDto, UpdateWarrantyClaimDto};
use crate::application::service::WarrantyClaimService;
use crate::domain::entity::WarrantyClaim;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateWarrantyClaimUseCase = CreateUseCase<WarrantyClaim, CreateWarrantyClaimDto, WarrantyClaimService>;
pub type UpdateWarrantyClaimUseCase = UpdateUseCase<WarrantyClaim, UpdateWarrantyClaimDto, WarrantyClaimService>;
pub type GetWarrantyClaimUseCase    = GetUseCase<WarrantyClaim, WarrantyClaimService>;
pub type DeleteWarrantyClaimUseCase = DeleteUseCase<WarrantyClaim, WarrantyClaimService>;
pub type ListWarrantyClaimUseCase   = ListUseCase<WarrantyClaim, WarrantyClaimService>;

// <<< CUSTOM
// END CUSTOM
